passage: 
  name: night
  values: [31, 32, 26, 25, 30, 33, 28, 29, 3, 27]

estimators:
  - lstm_ae
  - conv_lstm_ae
  - attn_ae
  - transformer
  - mne

window: 7680
perc: 1

thresholds: 
  lstm_ae: [-0.54, -0.02]
  conv_lstm_ae: [-0.62, -0.05]
  attn_ae: [-0.05, -0.01]
  transformer: [-13.77, -7.11]
  mne: [-119.64, -222.67]

# Threshold Suggestions {low, mid, high}
#--------------------------------------#
# lstm_ae: {[-1.42, -0.13], [-0.94, -0.07], [-0.54, -0.02]}
# conv_lstm_ae: {[-1.45, -0.14], [-0.98, -0.09], [-0.62, -0.05]}
# attn_ae: {[-0.10, -0.02], [-0.07, -0.02], [-0.05, -0.01]}
# transformer: {[-16.88, -8.70], [-15.32, -7.90], [-13.77, -7.11]}
# mne: {[-120.06, -223.06], [-119.85, -222.86], [-119.64, -222.67]}