passage: 
  name: night
  values: [32, 27]

estimators:
  - lstm_ae
  - conv_lstm_ae
  - attn_ae
  - transformer
  - mne

window: 7680
perc: 1

thresholds: 
  - lstm_ae: 5
  - conv_lstm_ae: 9
  - attn_ae: 1
  - transformer: 200
  - mne: ~