passage: 
  name: night
  values: [31, 32, 26, 25, 30, 33, 28, 29, 3, 27]

estimators:
  - lstm_ae
  - conv_lstm_ae
  - attn_ae_r
  - attn_ae_a
  - classifier
  - predictor_r
  - predictor_a
  - mne
  - cusum
  - page_hinkley
  - kl
  - adwin
  - pca

window: 7680
perc: 1

thresholds: 
  lstm_ae: [-0.05, 0.06]
  conv_lstm_ae: [0.05, 0.08]
  attn_ae_r: [-0.05, -0.01]
  attn_ae_a: [1, 1]
  classifier: [-13.77, -7.11]
  predictor_r: [1, 1]
  predictor_a: [1, 1]
  mne: [-1.06, -0.30]
  cusum: [0.5, 0.5]
  page_hinkley: [0.5, 0.5]
  kl: [0.5, 0.5]
  adwin: [0.5, 0.5]
  pca: [0.5, 0.5]

# Threshold Suggestions {95, 97, 99}
#--------------------------------------#
# lstm_ae: {[-0.05, 0.06], [0.05, 0.08], [0.24, 0.12]}
# conv_lstm_ae: {[-0.18, -0.01], [-0.09, 0.01], [0.07, 0.05]}
# attn_ae_r: {[0.32, 0.13], [0.43, 0.32], [0.61, 0.72]}
# attn_ae_a: {[0.31, 0.30], [0.31, 0.30], [0.31, 0.30]}
# classifier: {[4.77, 0.96], [4.77, 0.96], [4.77, 0.96]}
# predictor_r: {[0.58, 0.34], [0.71, 0.65], [0.90, 0.77]}
# predictor_a: {[1.44, 1.86], [1.44, 1.86], [1.44, 1.86]}
# mne: {[-1.06, -0.30], [-1.06, -0.30], [-1.05, -0.29]}